name: Terraform CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Target environment to deploy (e.g., blue, green)'
        required: false
        default: ''

env:
  TF_VAR_target_environment: ${{ github.event.inputs.target_environment || '' }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0  # Specify your desired Terraform version

      # Configure AWS credentials (if using AWS backend)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your region

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Run Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var="target_environment=${{ env.TF_VAR_target_environment }}"

      # Run Terraform Apply (only on push to main or manual trigger)
      - name: Terraform Apply
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve -var="target_environment=${{ env.TF_VAR_target_environment }}"